import { defineStore } from 'pinia';
import { ref } from 'vue';

export const useProduct = defineStore('products', () => {
  const products = ref([
    {
      id: 1,
      name: 'water yam',
      img: 'img/featured/feature-1.jpg',
      class: 'oranges fastfood vegetables',
      price: 2000,
      rate: { count: 10, rate: 4 },
      suppose_price: 25000,
      discount_price: 11000,
      desc: '',
    },
    {
      id: 2,
      name: 'sweet potato',
      img: 'img/featured/feature-2.jpg',
      class: 'vegetables rootfood',
      price: 1500,
      rate: { count: 25, rate: 3.5 },
      suppose_price: 22000,
      discount_price: 9000,
      desc: '',
    },
    {
      id: 3,
      name: 'carrot',
      img: 'img/featured/feature-3.jpg',
      class: 'vegetables freshfood',
      price: 1200,
      rate: { count: 18, rate: 4.2 },
      suppose_price: 18000,
      discount_price: 8000,
      desc: '',
    },
    {
      id: 4,
      name: 'orange',
      img: 'img/featured/feature-4.jpg',
      class: 'oranges fruits',
      price: 1000,
      rate: { count: 30, rate: 4.0 },
      suppose_price: 15000,
      discount_price: 7000,
      desc: '',
    },
    {
      id: 5,
      name: 'tomato',
      img: 'img/featured/feature-5.jpg',
      class: 'vegetables freshfood',
      price: 800,
      rate: { count: 40, rate: 4.5 },
      suppose_price: 12000,
      discount_price: 6000,
      desc: '',
    },
    {
      id: 6,
      name: 'onion',
      img: 'img/featured/feature-6.jpg',
      class: 'vegetables spices',
      price: 600,
      rate: { count: 22, rate: 3.8 },
      suppose_price: 11000,
      discount_price: 5000,
      desc: '',
    },
    {
      id: 7,
      name: 'banana',
      img: 'img/featured/feature-7.jpg',
      class: 'fruits snacks',
      price: 500,
      rate: { count: 33, rate: 4.6 },
      suppose_price: 10000,
      discount_price: 4500,
      desc: '',
    },
    {
      id: 8,
      name: 'apple',
      img: 'img/featured/feature-8.jpg',
      class: 'fruits freshfood',
      price: 3000,
      rate: { count: 15, rate: 4.8 },
      suppose_price: 20000,
      discount_price: 9000,
      desc: '',
    },
    {
      id: 9,
      name: 'lettuce',
      img: 'img/featured/feature-1.jpg',
      class: 'vegetables freshfood',
      price: 1200,
      rate: { count: 12, rate: 3.9 },
      suppose_price: 18000,
      discount_price: 8000,
      desc: '',
    },
    {
      id: 10,
      name: 'spinach',
      img: 'img/featured/feature-2.jpg',
      class: 'vegetables freshfood',
      price: 1400,
      rate: { count: 20, rate: 4.1 },
      suppose_price: 16000,
      discount_price: 7500,
      desc: '',
    },
    {
      id: 11,
      name: 'pineapple',
      img: 'img/featured/feature-3.jpg',
      class: 'fruits snacks',
      price: 3500,
      rate: { count: 9, rate: 4.7 },
      suppose_price: 25000,
      discount_price: 12000,
      desc: '',
    },
    {
      id: 12,
      name: 'grape',
      img: 'img/featured/feature-4.jpg',
      class: 'fruits freshfood',
      price: 3200,
      rate: { count: 24, rate: 4.3 },
      suppose_price: 24000,
      discount_price: 11000,
      desc: '',
    },
    {
      id: 13,
      name: 'strawberry',
      img: 'img/featured/feature-5.jpg',
      class: 'fruits freshfood',
      price: 4500,
      rate: { count: 14, rate: 4.9 },
      suppose_price: 30000,
      discount_price: 15000,
      desc: '',
    },
    {
      id: 14,
      name: 'eggplant',
      img: 'img/featured/feature-6.jpg',
      class: 'vegetables freshfood',
      price: 1800,
      rate: { count: 16, rate: 4.0 },
      suppose_price: 14000,
      discount_price: 6000,
      desc: '',
    },
    {
      id: 15,
      name: 'pumpkin',
      img: 'img/featured/feature-7.jpg',
      class: 'vegetables rootfood',
      price: 2200,
      rate: { count: 10, rate: 3.5 },
      suppose_price: 20000,
      discount_price: 9000,
      desc: '',
    },
    {
      id: 16,
      name: 'blueberry',
      img: 'img/featured/feature-8.jpg',
      class: 'fruits freshfood',
      price: 6000,
      rate: { count: 17, rate: 4.9 },
      suppose_price: 32000,
      discount_price: 17000,
      desc: '',
    },
    {
      id: 17,
      name: 'potato',
      img: 'img/featured/feature-1.jpg',
      class: 'vegetables rootfood',
      price: 1900,
      rate: { count: 28, rate: 4.2 },
      suppose_price: 17000,
      discount_price: 8000,
      desc: '',
    },
    {
      id: 18,
      name: 'mango',
      img: 'img/featured/feature-2.jpg',
      class: 'fruits freshfood',
      price: 2800,
      rate: { count: 35, rate: 4.6 },
      suppose_price: 22000,
      discount_price: 10000,
      desc: '',
    },
    {
      id: 19,
      name: 'ginger',
      img: 'img/featured/feature-3.jpg',
      class: 'vegetables spices',
      price: 3000,
      rate: { count: 11, rate: 4.4 },
      suppose_price: 19000,
      discount_price: 8500,
      desc: '',
    },
    {
      id: 20,
      name: 'papaya',
      img: 'img/featured/feature-4.jpg',
      class: 'fruits freshfood',
      price: 2600,
      rate: { count: 30, rate: 4.5 },
      suppose_price: 21000,
      discount_price: 9500,
      desc: '',
    },
  ]);

  return {
    products,
  };
});
